import express from "express";
import cors from "cors";
import path from "node:path";
import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const PORT=process.env.PORT||3000;
app.use(cors()); app.use(express.json({limit:"2mb"}));
app.use(express.static(path.join(__dirname,"public")));
app.get("/api/health",(req,res)=>res.json({ok:true,app:"ExcelWeb",version:"1.0.0"}));
app.get("/api/config",(req,res)=>res.json({features:["excel-catalog","image-vault","sshow","dual-vault","sra","ssi","rname","settings"]}));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("ExcelWeb running on http://localhost:"+PORT));